routes/web.php
<?php

use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Blog\HomeController@index');
Route::get('/temp/post/{post}', 'Blog\HomeController@post')->name('pst');
Route::post('/mpesa','MpesaController@index')->name('mpesa');


Auth::routes(
    [ 'register'=>false
    ]
);

Route::get('users/{id}', function ($id) {
    return View('auth.login');
});


Route::group(['middleware' => 'auth'], function() {
Route::get('posts/restore/{post}','PostsController@restored')->name('posts.restore');
Route::get('posts/trashed','PostsController@trashed')->name('posts.trashed');
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('category', 'CategoriesController');
Route::resource('posts','PostsController');
Route::resource('tag','TagsController');
Route::resource('subcategory','SubcategoryController');
Route::resource('user','UsersController');
Route::get('image','ImageController@index')->name('imagine');
Route::post('image/create','ImageController@create')->name('crop');
});

resources/views/pages/category.blade.php
@extends('layouts.app')

@push('css')
   <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach ($errors->all() as $erro)
                    <li class="list-group-item text-danger">
                        {{$erro}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

 <div class="card shadow mb-4">
            <div class="card-header py-3 bg-gradient-primary ">
              <a href="#" class=" btn btn-sm btn-primary shadow-sm"   data-toggle="modal" data-target="#createCategory"><i class="fas fa-plus fa-sm text-white-50"></i>Create category</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Category id</th>
                      <th>Category name</th>
                      <th>Tags of Category</th>
                      <th>Posts of Category</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach ($categories as $category)
                            <tr>
                                <td>{{$category->id}}</td>
                                <td>{{$category->name}}</td>
                                <td></td>
                                <td>{{$category->post->count()}}</td>
                                <td>
                                    <a href="#" class="btn btn-warning btn-circle btn-sm shadow-sm" onclick="update_cat({{$category->id}},'{{$category->name}}')"><i class="fas fa-edit"></i></a>
                                </td>
                                <td> 
                                    <a href="#" class="btn btn-danger btn-circle btn-sm shadow-sm" onclick="delete_cat({{$category->id}})"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach           
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {{--Modal of create and update category--}}


  <div class="modal fade" id="createCategory" tabindex="-1" role="dialog" aria-labelledby="category" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-gradient-primary">
            <span class="font-weight-bold" id="category">New category</span>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            
            <form id="category_create" action="{{ route('category.store') }}" method="POST">
                @csrf
                @method('POST')
                <div class="row">
                    <div class="col-sm-12">
                        <input type="text" name="name" class="form-control" placeholder="create Category">
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ route('category.store') }}" onclick="event.preventDefault();document.getElementById('category_create').submit();">Create</a>
          
        </div>
      </div>
    </div>
  </div>
{{-- update category modal--}}

  <div class="modal fade" id="UpdateCategory" tabindex="-1" role="dialog" aria-labelledby="category" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-gradient-warning">
          <span class="font-weight-bold" id="category_up">Update category</span>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            
            <form name="Update_Category" id="category_update" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-sm-12">
                        <input id="category_update_name" type="text" name="name" class="form-control" placeholder="update Category">
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary"  onclick="event.preventDefault();document.getElementById('category_update').submit();">Update</a>
          
        </div>
      </div>
    </div>
  </div>

{{--Modal of Delete category--}}




<div id="addNewAddonCategoryModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-gradient-danger">
                <h6 class="modal-title "><span class="font-weight-bold">Delete category</span></h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="alert alert-warning container">Are you sure ?</div>
                <form action="" method="POST" id="deleteCat">
                    @method('DELETE')
                    @csrf

               
                <button type="submit" class=" btn btn-primary btn-sm" data-dismiss="modal">
                        No . go back
                </button>
                <input type="submit" class="btn btn-danger btn-sm" value="yes . delete">
                        
                 </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function delete_cat(id){
        var form = document.getElementById('deleteCat');
        form.action = 'category/'+id;
        console.log(form);
        $('#addNewAddonCategoryModal').modal('show');
    };

    function update_cat(id,name) {
        var form  = document.getElementById('category_update');
        form.action = 'category/'+id;
        document.forms["Update_Category"]["name"].value = name;
        console.log(form);
        $('#UpdateCategory').modal('show');
    };


  




</script>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
  <!-- Page level custom scripts -->
  <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>
@endpush

resources/views/pages/post.blade.php
@extends('layouts.app')

@push('css')
   <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach ($errors->all() as $erro)
                    <li class="list-group-item text-danger">
                        {{$erro}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

 <div class="card shadow mb-4">
            <div class="card-header py-3 bg-gradient-primary ">
              <a href=" {{ route('posts.create') }}" class=" btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i>Create Post</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Image</th>
                      <th>Post Title</th>
                      <th>Post Category</th>
                      <th>Posts  Author</th>
                      <th>Edit</th>
                      <th>Trash</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach ($posts as $post)
                            <tr>
                                <td style="width: 120px; height: 30px"><img src="{{ asset('/storage') }}/{{$post->image}}" width="120px" height="30px"></td>
                                <td>{{$post->title}}</td>
                                <td style="text-transform:capitalize">{{$post->category->name}}</td>
                                <td style="text-transform:capitalize">{{$post->author->name}}</td>
                                
                                <td>
                                    <a href="{{ route('posts.edit',$post->id) }}" class="btn btn-warning btn-circle btn-sm shadow-sm"><i class="fas fa-edit"></i></a>
                                </td>
                                <td> 
                                    <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-circle btn-sm shadow-sm"><i class="fas fa-trash"></i></button>
                      
                    </form>
                                    
                                </td>
                            </tr>
                        @endforeach           
                  </tbody>
                </table>
              </div>
            </div>
 </div>
@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>

@endpush

resources/views/pages/subcategory.blade.php
@extends('layouts.app')

@push('css')
   <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach ($errors->all() as $erro)
                    <li class="list-group-item text-danger">
                        {{$erro}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif

 <div class="card shadow mb-4">
            <div class="card-header py-3 bg-gradient-primary ">
              <a href="#" class=" btn btn-sm btn-primary shadow-sm"   data-toggle="modal" data-target="#createSubcategory"><i class="fas fa-plus fa-sm text-white-50"></i>Create Subcategory</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Subcategory id</th>
                      <th>Subcategory name</th>
                      <th>Category of subcategory</th>
                      <th>Tags of subcategory</th>
                      <th>Posts of subcategory</th>
                      <th>Edit</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach ($subcategories as $subcategory)
                            <tr>
                                <td>{{$subcategory->id}}</td>
                                <td>{{$subcategory->name}}</td>
                                <td>{{$subcategory->category_id}}</td>
                                <td></td>
                                <td></td>
                                <td>
                                    <a href="#" class="btn btn-warning btn-circle btn-sm shadow-sm" onclick="update_cat({{$subcategory->id}},'{{$subcategory->name}}')"><i class="fas fa-edit"></i></a>
                                </td>
                                <td> 
                                    <a href="#" class="btn btn-danger btn-circle btn-sm shadow-sm" onclick="delete_cat({{$subcategory->id}})"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                        @endforeach           
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {{--Modal of create and update Subcategory--}}


  <div class="modal fade" id="createSubcategory" tabindex="-1" role="dialog" aria-labelledby="Subcategory" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-gradient-primary">
            <span class="font-weight-bold" id="Subcategory">New Subcategory</span>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            
            <form id="Subcategory_create" action="{{ route('subcategory.store') }}" method="POST">
                @csrf
                @method('POST')
                <div class="row">
                    <div class="col-sm-12">
                        <input type="text" name="name" class="form-control" placeholder="create Subcategory">
                    </div>
                    <div class=" py-2 col-sm-12">
                       <select name="category_id" class="form-control custom-select">
                            <option disabled="true" selected>Subcategory  category ...</option>
                            @foreach ($categories as $category)
                                <option  value="{{$category->id}}"
                                    @if (isset($subcategory) && ($category->id==$subcategory->category_id))
                                        selected 
                                    @endif
                                    >{{$category->name}}</option>
                            @endforeach
                       </select>
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{{ route('subcategory.store') }}" onclick="event.preventDefault();document.getElementById('Subcategory_create').submit();">Create</a>
          
        </div>
      </div>
    </div>
  </div>
{{-- update Subcategory modal--}}

  <div class="modal fade" id="UpdateSubcategory" tabindex="-1" role="dialog" aria-labelledby="Subcategory" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header bg-gradient-warning">
          <span class="font-weight-bold" id="Subcategory_up">Update Subcategory</span>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
            
            <form name="Update_Subcategory" id="Subcategory_update" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-sm-12">
                        <input id="Subcategory_update_name" type="text" name="name" class="form-control" placeholder="update Subcategory">
                    </div>
                    <div class=" py-2 col-sm-12">
                       <select name="category_id" class="form-control custom-select">
                            <option disabled="true" selected>Subcategory  category ...</option>
                            @foreach ($categories as $category)
                                <option  value="{{$category->id}}"
                                    @if (isset($subcategory) && ($category->id==$subcategory->category_id))
                                        selected 
                                    @endif
                                    >{{$category->name}}</option>
                            @endforeach
                       </select>
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary"  onclick="event.preventDefault();document.getElementById('Subcategory_update').submit();">Update</a>
          
        </div>
      </div>
    </div>
  </div>

{{--Modal of Delete Subcategory--}}




<div id="addNewAddonSubcategoryModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header bg-gradient-danger">
                <h6 class="modal-title "><span class="font-weight-bold">Delete Subcategory</span></h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="alert alert-warning container">Are you sure ?</div>
                <form action="" method="POST" id="deleteCat">
                    @method('DELETE')
                    @csrf

               
                <button type="submit" class=" btn btn-primary btn-sm" data-dismiss="modal">
                        No . go back
                </button>
                <input type="submit" class="btn btn-danger btn-sm" value="yes . delete">
                        
                 </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function delete_cat(id){
        var form = document.getElementById('deleteCat');
        form.action = 'subcategory/'+id;
        console.log(form);
        $('#addNewAddonSubcategoryModal').modal('show');
    };

    function update_cat(id,name) {
        var form  = document.getElementById('Subcategory_update');
        form.action = 'subcategory/'+id;
        document.forms["Update_Subcategory"]["name"].value = name;
        console.log(form);
        $('#UpdateSubcategory').modal('show');
    };


  




</script>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>

@endpush

resources/views/pages/trashedPost.blade.php
@extends('layouts.app')
@push('css')
   <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush

@section('content')


 <div class="card shadow mb-4">
            <div class="card-header py-3 bg-gradient-primary ">
              <a href=" {{ route('posts.create') }}" class=" btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i>Create Post</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>Image</th>
                      <th>Post Title</th>
                      <th>Post Category</th>
                      <th>Posts  Author</th>
                      <th>Restore</th>
                      <th>Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach ($posts as $post)
                              @if ($post->trashed())
                            <tr>
                                <td style="width: 120px; height: 30px"><img src="{{ asset('/storage') }}/{{$post->image}}" width="120px" height="30px"></td>
                                <td>{{$post->title}}</td>
                                <td>{{$post->category_id}}</td>
                                <td>{{$post->author_id}}</td>
                                
                                <td>
                                    <form action="{{ route('posts.restore',$post->id) }}" method="post">
                                        @csrf
                                        @method('get')
                                        <input type="submit" class="btn btn-primary btn-sm shadow-sm" value="Restore">
                                    </form>


                                    

                                </td>
                                <td> 
                                    <form action="{{ route('posts.destroy',$post->id) }}" method="POST">
                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger btn-circle btn-sm shadow-sm"><i class="fas fa-trash"></i></button>
                      
                    </form>
                                    
                                </td>
                            </tr>
                            @endif
                        @endforeach           
                  </tbody>
                </table>
              </div>
            </div>
 </div>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>

@endpush

resources/views/pages/user.blade.php
@extends('layouts.app')

@push('css')
   <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endpush
@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="list-group">
                @foreach ($errors->all() as $erro)
                    <li class="list-group-item text-danger">
                        {{$erro}}
                    </li>
                @endforeach
            </ul>
        </div>
    @endif


 <style>
     .user,.card-img-top{
        border-radius: 0rem !important;
        border:none !important;
     }
     .user{
       box-shadow:  0 14px 24px 0 rgba(50, 48, 57, 0.25);
     }
     .user-card{
        color: black;position: relative;
        font-style: bold;
        text-transform: capitalize;
        text-align: center;
        font-weight: bold;
     }
 </style>
<div class="container">
    <div>
    <a href=" {{ route('user.create') }}" class=" btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i>Create User</a></div>
    <div class="row">


    @foreach ($users as $user)
        <div class="col-md-6 col-lg-4 col-xl-3  col-sm-6 py-3">
        <div class="card m-b-30 user" style="border-radius: none">
                 <img class="card-img-top img-fluid" src="{{ asset('/storage') }}/{{$user->image}}" alt="Card image cap" style="height: 234.75px; " >
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item user-card">
                        <div class="row">
                                
                                <div class="col-sm-12">
                                  {{ __('User:') }}&nbsp<small>{{$user->name}}</small> &nbsp <span class="badge badge-success shadow-sm">Amin</span>
                                </div>
                                
                            </div>
                        </li>
                        <li class="list-group-item user-card">{{ __('Posts: ') }} &nbsp 43</li>
                      </ul>

                  <div class="card-body">
                    
                    <div class="row">
                                <div class="col-sm-6">
                                     <button onclick='location.href="{{ route('user.edit',$user->id) }}"' class="btn btn-warning  btn-sm "><i class="fas fa-edit"></i> &nbsp Edit</button>
                                </div>
                                
                                <div class="col-sm-6">
                                    <form  action="{{ route('user.destroy',$user->id) }}" method="POST">@csrf @method('DELETE')<button type="submit" class="btn btn-danger  btn-sm "><i class="fas fa-trash"></i>&nbsp Delete</button></form>
                                </div>
                            </div>
                            
                  </div>                                    
        </div>
        </div> 
    @endforeach
</div>    
</div>



 {{--<div class="card shadow mb-4">
            <div class="card-header py-3 bg-gradient-primary ">
              <a href=" {{ route('user.create') }}" class=" btn btn-sm btn-primary shadow-sm"><i class="fas fa-plus fa-sm text-white-50"></i>Create User</a>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                      <th>#id</th>
                      <th>Image</th>
                      <th>Username</th>
                      <th>Email</th>
                      <th>Edit</th>
                      <th>Trash</th>
                    </tr>
                  </thead>
                  <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>{{$user->id}}</td>
                                <td style="width: 120px; height: 30px"><img src="{{ asset('/storage') }}/{{$user->image}}" width="120px" height="30px"></td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                
                                <td>
                                    <a href="{{ route('user.edit',$user->id) }}" class="btn btn-warning btn-circle btn-sm shadow-sm"><i class="fas fa-edit"></i></a>
                                </td>
                                <td> 
                                    <form action="{{ route('user.destroy',$user->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger btn-circle btn-sm shadow-sm"><i class="fas fa-trash"></i></button>
                                      
                                    </form>
                                    
                                </td>
                            </tr>}}
                        @endforeach           
                  </tbody>
                </table>
              </div>
            </div>
 </div>--}}
@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
  <script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>

  <!-- Page level custom scripts -->
  <script src="{{ asset('js/demo/datatables-demo.js') }}"></script>

@endpush